version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medtnr-backend
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal # Connects to MySQL running outside Docker
      - DB_USER=root
      - DB_PASSWORD=Password123
      - DB_NAME=medtnr_inventory
      - DB_PORT=3306
    volumes:
      - ./Backend:/home/node/app/Backend
    restart: unless-stopped
